### ISSUE TITLE
Issue: Scalar from_hash not found for current scope

### ISSUE THREAD

**Issue by ValValu** [wavesplatform/waves-rust#54]
error[E0599]: no function or associated item named `from_hash` found for struct `Scalar` in the current scope
  --> /Users/val/.cargo/registry/src/github.com-1ecc6299db9ec823/waves-rust-0.1.0/src/util/crypto.rs:77:27
   |
77 |         let rsc = Scalar::from_hash(hash);
   |                           ^^^^^^^^^ function or associated item not found in `Scalar`

**Comment by devyatkinalexandr** [comment]
I guess it can be due to the problem with dependency resolution.
Could you try to add this lines in your root toml file
```
[patch.crates-io]
curve25519-dalek = { git = "https://github.com/nazar-pc/curve25519-dalek", branch="relax-zeroize", version = "4.0.0-pre.2"}
```
and then run `cargo update` to update your lock file.
It should fix the problem
